{% set name = "qiskit-ibm-runtime" %}
{% set version = "0.9.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qiskit-ibm-runtime-{{ version }}.tar.gz
  sha256: 5aa69ee8199556306378644e8dc773c901424bf2d49e5d68ff74b4c34bb1ddd5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - qiskit-terra >=0.24.0
    - requests >=2.19
    - requests_ntlm >=1.1.0
    - numpy <1.24
    - urllib3 >=1.21.1
    - python-dateutil >=2.8.0
    - websocket-client >=1.5.1
    - typing-extensions >=4.0.0
    - ibm-platform-services >=0.22.6

test:
  imports:
    - qiskit_ibm_runtime
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Qiskit/qiskit-ibm-runtime
  summary: IBM Quantum client for Qiskit Runtime.
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - wshanks
