{% set name = "qiskit-ibm-runtime" %}
{% set version = "0.31.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 935ceac221c5af95ba86996f77872850b7d5975d776e507b372ff8148c90a215

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - pydantic >=2.5.0
    - qiskit >=1.1.0
    - python >=3.8
    - requests >=2.19
    - requests_ntlm >=1.1.0
    - numpy >=1.13
    - urllib3 >=1.21.1
    - python-dateutil >=2.8.0
    - websocket-client >=1.5.1
    - ibm-platform-services >=0.22.6

test:
  imports:
    - qiskit_ibm_runtime
  commands:
    - pip check
  requires:
    - pip
    - python <3.13  # requests_ntlm has not 3.13 build yet

about:
  home: https://github.com/Qiskit/qiskit-ibm-runtime
  summary: IBM Quantum client for Qiskit Runtime.
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - wshanks
