{% set name = "qiskit-ibm-runtime" %}
{% set version = "0.37.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 656e8c97730125cd82c910722eefd3dc5bd4d22a7a8f868735629001995646e1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=40.6.0
    - setuptools_scm >=6.2
  run:
    - packaging
    - pydantic >=2.5.0,<2.10
    - qiskit >=1.4.1
    - python >={{ python_min }}
    - requests >=2.19
    - requests_ntlm >=1.1.0
    - numpy >=1.13
    - urllib3 >=1.21.1
    - python-dateutil >=2.8.0
    - websocket-client >=1.5.1
    - ibm-platform-services >=0.22.6

test:
  imports:
    - qiskit_ibm_runtime
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}  # requests_ntlm dependency pyspegno has no 3.13 build yet

about:
  home: https://github.com/Qiskit/qiskit-ibm-runtime
  summary: IBM Quantum client for Qiskit Runtime.
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - wshanks
