{% set name = "qiskit-ibm-runtime" %}
{% set version = "0.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qiskit-ibm-runtime-{{ version }}.tar.gz
  sha256: e7b82f6a2fbbbe8d3ee6cab84a05cb62cccab73b528a0b22d9d52688c9bac9a4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - qiskit >=0.44.1
    - qiskit-ibm-provider >=0.7.2
    - python >=3.8
    - requests >=2.19
    - requests_ntlm >=1.1.0
    - numpy >=1.13
    - urllib3 >=1.21.1
    - python-dateutil >=2.8.0
    - websocket-client >=1.5.1
    - ibm-platform-services >=0.22.6

test:
  imports:
    - qiskit_ibm_runtime
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Qiskit/qiskit-ibm-runtime
  summary: IBM Quantum client for Qiskit Runtime.
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - wshanks
