schema_version: 1

context:
  name: qiskit-ibm-runtime
  version: 0.46.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 22d0fa71ccffd9db03f19e3d05fc5da6bacdf54bb5a8347b25a275623de82645

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=40.6.0
    - setuptools_scm >=6.2
  run:
    - ibm-platform-services >=0.55.3
    - numpy >=1.26
    - packaging
    - pydantic >=2.7.0
    - python >=${{ python_min }}
    - python-dateutil >=2.9.0
    - qiskit >=2.2.0
    - requests >=2.32.4
    - requests_ntlm >=1.1.0
    - urllib3 >=2.4.0
    - pybase64 >=1.4
    - samplomatic >=0.13.0
    - ibm-quantum-schemas >=0.5.20260320
tests:
  - python:
      imports:
        - qiskit_ibm_runtime
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: IBM Quantum client for Qiskit Runtime.
  license: Apache-2.0
  license_file: LICENSE.txt
  homepage: https://github.com/Qiskit/qiskit-ibm-runtime

extra:
  recipe-maintainers:
    - wshanks
