schema_version: 1

context:
  name: qiskit-ibm-runtime
  version: 0.45.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 54b29d6e5201b038015f20e30ab90f846a3233a53e758f405a4c5a556fadb0bb

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=40.6.0
    - setuptools_scm >=6.2
  run:
    - ibm-platform-services >=0.22.6
    - numpy >=1.13
    - packaging
    - pydantic >=2.5.0
    - python >=${{ python_min }}
    - python-dateutil >=2.8.0
    - qiskit >=2.0.0
    - requests >=2.19,!=2.32.2
    - urllib3 >=1.21.1
    - requests-ntlm >=1.1.0
tests:
  - python:
      imports:
        - qiskit_ibm_runtime
  - requirements:
      run:
        - pip
        - python ${{ python_min }}
    script:
      - pip check

about:
  summary: IBM Quantum client for Qiskit Runtime.
  license: Apache-2.0
  license_file: LICENSE.txt
  homepage: https://github.com/Qiskit/qiskit-ibm-runtime

extra:
  recipe-maintainers:
    - wshanks
